# Output Block

trigger:
  - main

pool:
  name: amit_test

stages:
  - stage: init_stage
    displayName: Terraform Init
    jobs:
      - job: terraforminit
        displayName: Terraform Init wala
        steps:
          - template: template/terraform-inst.yml
          - template: template/terraform-init.yml

  - stage: plan_stage
    displayName: Terraform Plan
    jobs:
      - job: terraformplan
        steps:
          - template: template/terraform-inst.yml
          - template: template/terraform-init.yml        
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
              environmentServiceNameAzureRM: 'output_connection'


